export const AUDIT_EVENTS = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",

  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_DELETED: "PROJECT_DELETED",

  PROJECT_ACTIVATED: "PROJECT_ACTIVATED",
  PROJECT_DEACTIVATED: "PROJECT_DEACTIVATED",

  BRIDGE_STARTED: "BRIDGE_STARTED",
};
